spring:
  datasource:
    url: jdbc:mysql://localhost:3306/custom_queries02
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
